version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
artifacts:
  files:
    - target/polls-0.1.0.jar
  discard-paths: yes
